[package]
name = "diorama"
version = "0.1.0"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"

[dev-dependencies]
reqwest = "0.9.2"
diorama-core = { path = "../diorama-core" }
diorama-derive = { path = "../diorama-derive" }