[package]
name = "diorama-example"
version = "0.1.0"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"

[dependencies]
diorama = { path = "./diorama" }
diorama_derive = { path = "./diorama_derive" }
reqwest = "0.9.2"