[package]
name = "diorama"
version = "0.1.0"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
reqwest = "0.9.2"

[lib]
crate-type = ["proc-macro"]
proc_macro = true